#!/usr/bin/env ruby

require 'time'
puts "postgres DUMP_PATH DB_NAME [FROM_TABLE] [TO_TABLE]"

dump_path = ARGV[0]
db = ARGV[1]

from_table = ARGV[2]
to_table = ARGV[3]

if from_table && to_table
  restore_command = "pg_restore --data-only --table=#{from_table} #{dump_path} | sed -e \"s/#{from_table}/#{to_table}/\" | psql -h \"$POSTGRES_PORT_5432_TCP_ADDR\" -p \"$POSTGRES_PORT_5432_TCP_PORT\" -U postgres #{db}"
else
  restore_command = "pg_restore -h \"$POSTGRES_PORT_5432_TCP_ADDR\" -p \"$POSTGRES_PORT_5432_TCP_PORT\" -U postgres --clean --create #{dump_path} --dbname=#{db}"
end

puts "Calling #{restore_command} ..."
system(restore_command)

psql_command = "psql -h \"$POSTGRES_PORT_5432_TCP_ADDR\" -p \"$POSTGRES_PORT_5432_TCP_PORT\" -U postgres #{db} -c '\\dt'"
puts "Import may be ready"
system(psql_command)

$?.exitstatus
